{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  config.yaml: |
    discord:
      guild_id: {{ .Values.config.discord.guild_id | quote }}
      {{- if .Values.botTokens }}
      bot_tokens:
        {{- range .Values.botTokens }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    livekit:
      url: {{ .Values.config.livekit.url | quote }}
      api_key: {{ .Values.config.livekit.api_key | quote }}
      api_secret: {{ .Values.config.livekit.api_secret | quote }}
    matrix:
      homeserver_url: {{ .Values.config.matrix.homeserver_url | quote }}
      as_token: {{ .Values.config.matrix.as_token | quote }}
      server_name: {{ .Values.config.matrix.server_name | quote }}
      lk_jwt_service_url: {{ .Values.config.matrix.lk_jwt_service_url | quote }}
      {{- if .Values.config.matrix.admin_users }}
      admin_users:
        {{- range .Values.config.matrix.admin_users }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    log_level: {{ .Values.config.log_level | quote }}
{{- end }}
